### PR TITLE
Update kuzzle-sdk

### PR DESCRIPTION
**Pull request by Aschen**
## What does this PR do ?

Updates cucumber to use the latest version of the SDK

### How should this be manually tested?

`npm run functional-testing`

### CODE REVIEW

**Review by etrousset — APPROVED** [review]

**Review by scottinet — APPROVED** [review]

**Review by scottinet — CHANGES_REQUESTED** [review]
You have to increase the version number if you want to merge directly on the `master` branch: run `npm version patch` and push the result on github

**Comment by Aschen** [comment]
> npm version patch

I didn't know this command to upgrade the package.json version !
Done.

**Comment by scottinet** [comment]
This command also updates the version number in the `package-lock.json` file, which is handy :slightly_smiling_face:

**Review by scottinet — APPROVED** [review]

**Review by scottinet — CHANGES_REQUESTED** [review]
It seems that you forgot to push the `npm version patch` result.

**Review by scottinet — APPROVED** [review]

**Pull request merged**
